from rclpy.context import Context as Context
from rclpy.executors import Executor as Executor
from rclpy.node import Node as Node
from rclpy.parameter import Parameter as Parameter
from rclpy.signals import SignalHandlerOptions as SignalHandlerOptions, install_signal_handlers as install_signal_handlers, uninstall_signal_handlers as uninstall_signal_handlers
from rclpy.task import Future as Future
from rclpy.utilities import get_default_context as get_default_context, get_rmw_implementation_identifier as get_rmw_implementation_identifier, ok as ok, try_shutdown as try_shutdown

def init(*, args: list[str] | None = None, context: Context = None, domain_id: int | None = None, signal_handler_options: SignalHandlerOptions | None = None) -> None: ...
def get_global_executor() -> Executor: ...
def shutdown(*, context: Context = None, uninstall_handlers: bool | None = None) -> None: ...
def create_node(node_name: str, *, context: Context = None, cli_args: list[str] = None, namespace: str = None, use_global_arguments: bool = True, enable_rosout: bool = True, start_parameter_services: bool = True, parameter_overrides: list[Parameter] = None, allow_undeclared_parameters: bool = False, automatically_declare_parameters_from_overrides: bool = False) -> Node: ...
def spin_once(node: Node, *, executor: Executor = None, timeout_sec: float = None) -> None: ...
def spin(node: Node, executor: Executor = None) -> None: ...
def spin_until_future_complete(node: Node, future: Future, executor: Executor = None, timeout_sec: float = None) -> None: ...
